### PR TITLE
Fix redhat pd tools install

### PR DESCRIPTION
**Pull request by cjlapao**
This will fix the issue where in some situations the tools would fail to install by moving it to be the first thing to install before setting up the vm

### CODE REVIEW

**Comment by cjlapao** [comment]
Yes, your solution was better, this was closed not merged

**Comment by stephenulmer** [comment]
Sorry, was trying to unwind the comment! Didn't understand. :(

**Comment by cjlapao** [comment]
@stephenulmer 

This branch was closed without merging, so your solution is the one in main as it is the better solution.

Makes sense?

**Comment by stephenulmer** [comment]
I understand now, I had just misinterpreted what GitHub was showing me. After I updated, I understood what happened and was trying to delete my comment, but you beat me to responding. :)

**Pull request closed without merging**
